# Generated by Django 6.0.5 on 2026-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('skill', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Design', 'Design'), ('DevOps', 'DevOps'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('experience_years', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('skill', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Design', 'Design'), ('DevOps', 'DevOps'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
