# Generated by Django 6.0.5 on 2026-05-16 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead_freelancer_lead_user_alter_lead_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='core.freelancer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, choices=[('Startup', 'Startup'), ('Agenție', 'Agenție'), ('Corporație', 'Corporație'), ('ONG', 'ONG'), ('Persoană fizică', 'Persoană fizică'), ('Altele', 'Altele')], max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.clientprofile'),
        ),
    ]
